### ISSUE TITLE
Проблем при логване

### ISSUE THREAD

**Issue by SavinaDzhenimova** [luchob/softuni-spring-may-2024#15]
https://github.com/SavinaDzhenimova/HomeDeliveryApp

Премахнах валидацията за парола от миналото issue, което публикувах, за да успея да запиша потребител в базата данни и да изпробвам логването в системата. Оказа се, че при логване с правилни username и password получавам следната грешка:

org.springframework.security.authentication.InternalAuthenticationServiceException: Error creating bean with name 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties': Could not bind properties to 'DataSourceProperties' : prefix=spring.datasource, ignoreInvalidFields=false, ignoreUnknownFields=true
at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:110)
    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:93)

Като грешката завършва с това:
2024-07-01T13:50:09.162+03:00 ERROR 13488 --- [nio-8090-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] threw exception

java.lang.StackOverflowError: null
	at jakarta.servlet.ServletRequestWrapper.isAsyncStarted(ServletRequestWrapper.java:368) ~[tomcat-embed-core-10.1.25.jar:6.0]
	at jakarta.servlet.ServletRequestWrapper.isAsyncStarted(ServletRequestWrapper.java:368) ~[tomcat-embed-core-10.1.25.jar:6.0]
	at jakarta.servlet.ServletRequestWrapper.isAsyncStarted(ServletRequestWrapper.java:368) ~[tomcat-embed-core-10.1.25.jar:6.0]
        .....

Търсих в интернет решения и най-честото предложение беше създаване на AuthenticationManager, но и това не помогна да отстраня проблема.

**Comment by luchob** [comment]
Здравей!

Хах, това беше добро :-) Първият проблем е, че всъщност никога не си се логвала с правилно име и парола. Причината е в конфигурацията ти:

```
                        .loginPage("/users/login").permitAll()
                        .usernameParameter("username")
                        .usernameParameter("password") 
                        .defaultSuccessUrl("/home", true)
                        .failureForwardUrl("/users/login")
```
Или по-точно този ред.

```
usernameParameter("password") 
``` 
Където всъщност казваш че юзърнейма идва от поле с име `password`. 

Следващият проблем е в този ред:

```
.failureForwardUrl("/users/login")
``` 

Как работи това, първо виж [тук](https://github.com/luchob/softuni-spring-may-2024/issues/6). Това, което се получава е, че при неуспешен логин както досега е бил всеки един логин Spring редиректва с POST към `/users/login`, което пък е логин ендпойнта създаден от spring security за логин и отново се опитва логин и отново фейлва и т.н. в infinite loop докато не завърши с StackOverflowError. Направи го да не е към `/users/login`, а към нещо твое като `/users/login-error` или подобно.

Поздрави,
Л.
